<a href="https://colab.research.google.com/github/NikitaN65/HelloWorld/blob/main/Copy_of_flat_animals_cbm_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [75]:
data = pd.read_csv('/content/predicate-matrix-binary.txt', sep=" ", header=None)
animals = pd.read_csv('/content/classes.txt', header=None)
animals.iloc[:, 0] = animals.iloc[:, 0].str.replace('[^a-zA-Z0-9]', '')
animals.iloc[:, 0] = animals.iloc[:, 0].str.replace(r'\d+', '', regex=True)
features = pd.read_csv('/content/predicates.txt', header=None)
features.iloc[:, 0] = features.iloc[:, 0].str.replace('[^a-zA-Z0-9]', '')
features.iloc[:, 0] = features.iloc[:, 0].str.replace(r'\d+', '', regex=True)
data.insert(0, 'animal', animals.iloc[:, 0])
data = data.set_index('animal')

<ipython-input-75-29e9e049a496>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  animals.iloc[:, 0] = animals.iloc[:, 0].str.replace('[^a-zA-Z0-9]', '')
<ipython-input-75-29e9e049a496>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  features.iloc[:, 0] = features.iloc[:, 0].str.replace('[^a-zA-Z0-9]', '')


In [76]:
features = features.T
data = data.append(features)
# select the row to move to the top
top_row = data.iloc[50:84, :]

# remove the selected row from the original dataframe
data = data.drop(top_row.index)

# concatenate the selected row with the remaining rows in the dataframe
data = pd.concat([top_row, data])

new_header = data.iloc[0] #grab the first row for the header
data = data[1:] #take the data less the header row
data.columns = new_header #set the header row as the df header
print(data)

0              black white blue brown gray orange red yellow patches spots  \
antelope           0     0    0     0    0      0   0      0       0     0   
grizzlybear        1     0    0     1    0      0   0      0       0     0   
killerwhale        1     1    0     0    0      0   0      0       1     1   
beaver             0     0    0     1    0      0   0      0       0     0   
dalmatian          1     1    0     0    0      0   0      0       1     1   
persiancat         0     1    1     0    1      0   0      0       0     0   
horse              1     1    0     1    1      0   0      0       1     0   
germanshepherd     1     0    0     1    1      0   0      0       1     0   
bluewhale          0     0    1     0    1      0   0      0       0     1   
siamesecat         1     1    0     1    1      0   0      0       1     0   
skunk              1     1    0     0    0      0   0      0       0     0   
mole               1     0    0     1    1      0   0      0    

In [77]:
col_to_move = 'forest'
data[col_to_move] = data.pop(col_to_move)

print(data)

0              black white blue brown gray orange red yellow patches spots  \
antelope           0     0    0     0    0      0   0      0       0     0   
grizzlybear        1     0    0     1    0      0   0      0       0     0   
killerwhale        1     1    0     0    0      0   0      0       1     1   
beaver             0     0    0     1    0      0   0      0       0     0   
dalmatian          1     1    0     0    0      0   0      0       1     1   
persiancat         0     1    1     0    1      0   0      0       0     0   
horse              1     1    0     1    1      0   0      0       1     0   
germanshepherd     1     0    0     1    1      0   0      0       1     0   
bluewhale          0     0    1     0    1      0   0      0       0     1   
siamesecat         1     1    0     1    1      0   0      0       1     0   
skunk              1     1    0     0    0      0   0      0       0     0   
mole               1     0    0     1    1      0   0      0    

In [78]:
data = data.drop(['newworld', 'oldworld', 'arctic', 'coastal', 'desert','bush','plains','fields','jungle','mountains','ocean','ground','water','tree','cave'], axis=1)
print(data)

0              black white blue brown gray orange red yellow patches spots  \
antelope           0     0    0     0    0      0   0      0       0     0   
grizzlybear        1     0    0     1    0      0   0      0       0     0   
killerwhale        1     1    0     0    0      0   0      0       1     1   
beaver             0     0    0     1    0      0   0      0       0     0   
dalmatian          1     1    0     0    0      0   0      0       1     1   
persiancat         0     1    1     0    1      0   0      0       0     0   
horse              1     1    0     1    1      0   0      0       1     0   
germanshepherd     1     0    0     1    1      0   0      0       1     0   
bluewhale          0     0    1     0    1      0   0      0       0     1   
siamesecat         1     1    0     1    1      0   0      0       1     0   
skunk              1     1    0     0    0      0   0      0       0     0   
mole               1     0    0     1    1      0   0      0    

In [79]:
Y = data['forest']
data = data.drop(['forest'], axis=1)

In [80]:
print(data)

0              black white blue brown gray orange red yellow patches spots  \
antelope           0     0    0     0    0      0   0      0       0     0   
grizzlybear        1     0    0     1    0      0   0      0       0     0   
killerwhale        1     1    0     0    0      0   0      0       1     1   
beaver             0     0    0     1    0      0   0      0       0     0   
dalmatian          1     1    0     0    0      0   0      0       1     1   
persiancat         0     1    1     0    1      0   0      0       0     0   
horse              1     1    0     1    1      0   0      0       1     0   
germanshepherd     1     0    0     1    1      0   0      0       1     0   
bluewhale          0     0    1     0    1      0   0      0       0     1   
siamesecat         1     1    0     1    1      0   0      0       1     0   
skunk              1     1    0     0    0      0   0      0       0     0   
mole               1     0    0     1    1      0   0      0    

In [81]:
# data['colour'] = pd.Series()
# data['skin'] = pd.Series()
# data['bodytype'] = pd.Series()
# data['limbs'] = pd.Series()
# data['extremities'] = pd.Series()
# data['teeth'] = pd.Series()
# data['personality'] = pd.Series()
# data['movement'] = pd.Series()
# data['food'] = pd.Series()
# data['hunting'] = pd.Series()
# print(data)

In [82]:
features = features.T
print(features)
features = features.drop([62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77], axis=0)
features = features.reset_index(drop=True)
print(features)
features.loc[[0,1,2,3,4,5,6,7], 'colour'] = 1
features['colour'] = features['colour'].fillna(0)
features.loc[[8,9,10,11,12,13], 'skin'] = 1
features['skin'] = features['skin'].fillna(0)
features.loc[[14,15,16,17,39,40,41,42,43], 'bodytype'] = 1
features['bodytype'] = features['bodytype'].fillna(0)
features.loc[[18,19,20,21,22,23,44,45], 'limbs'] = 1
features['limbs'] = features['limbs'].fillna(0)
features.loc[[18,19,20,21,22,23], 'limbs'] = 1
features['limbs'] = features['limbs'].fillna(0)
features.loc[[24,25,30,31,32], 'extremities'] = 1
features['extremities'] = features['extremities'].fillna(0)
features.loc[[26,27,28,29], 'teeth'] = 1
features['teeth'] = features['teeth'].fillna(0)
features.loc[[33,46,47,48,49,50,62,63,64,65,66,67,68], 'personality'] = 1
features['personality'] = features['personality'].fillna(0)
features.loc[[34,35,36,37,38], 'movement'] = 1
features['movement'] = features['movement'].fillna(0)
features.loc[[51,52,53,54,55], 'food'] = 1
features['food'] = features['food'].fillna(0)
features.loc[[56,57,58,59,60,61], 'hunting'] = 1
features['hunting'] = features['hunting'].fillna(0)
print(features)

           0
0      black
1      white
2       blue
3      brown
4       gray
..       ...
80     smart
81     group
82  solitary
83  nestspot
84  domestic

[85 rows x 1 columns]
           0
0      black
1      white
2       blue
3      brown
4       gray
..       ...
64     smart
65     group
66  solitary
67  nestspot
68  domestic

[69 rows x 1 columns]
           0  colour  skin  bodytype  limbs  extremities  teeth  personality  \
0      black     1.0   0.0       0.0    0.0          0.0    0.0          0.0   
1      white     1.0   0.0       0.0    0.0          0.0    0.0          0.0   
2       blue     1.0   0.0       0.0    0.0          0.0    0.0          0.0   
3      brown     1.0   0.0       0.0    0.0          0.0    0.0          0.0   
4       gray     1.0   0.0       0.0    0.0          0.0    0.0          0.0   
..       ...     ...   ...       ...    ...          ...    ...          ...   
64     smart     0.0   0.0       0.0    0.0          0.0    0.0          1.0   
65

In [83]:
concepts = features
concepts = concepts.set_index(0)
print(concepts)

          colour  skin  bodytype  limbs  extremities  teeth  personality  \
0                                                                          
black        1.0   0.0       0.0    0.0          0.0    0.0          0.0   
white        1.0   0.0       0.0    0.0          0.0    0.0          0.0   
blue         1.0   0.0       0.0    0.0          0.0    0.0          0.0   
brown        1.0   0.0       0.0    0.0          0.0    0.0          0.0   
gray         1.0   0.0       0.0    0.0          0.0    0.0          0.0   
...          ...   ...       ...    ...          ...    ...          ...   
smart        0.0   0.0       0.0    0.0          0.0    0.0          1.0   
group        0.0   0.0       0.0    0.0          0.0    0.0          1.0   
solitary     0.0   0.0       0.0    0.0          0.0    0.0          1.0   
nestspot     0.0   0.0       0.0    0.0          0.0    0.0          1.0   
domestic     0.0   0.0       0.0    0.0          0.0    0.0          1.0   

          m

In [86]:
data = data.T
print(data)

0              black white blue brown gray orange red yellow patches spots  \
antelope           0     0    0     0    0      0   0      0       0     0   
grizzlybear        1     0    0     1    0      0   0      0       0     0   
killerwhale        1     1    0     0    0      0   0      0       1     1   
beaver             0     0    0     1    0      0   0      0       0     0   
dalmatian          1     1    0     0    0      0   0      0       1     1   
persiancat         0     1    1     0    1      0   0      0       0     0   
horse              1     1    0     1    1      0   0      0       1     0   
germanshepherd     1     0    0     1    1      0   0      0       1     0   
bluewhale          0     0    1     0    1      0   0      0       0     1   
siamesecat         1     1    0     1    1      0   0      0       1     0   
skunk              1     1    0     0    0      0   0      0       0     0   
mole               1     0    0     1    1      0   0      0    

In [87]:
print(concepts)

          colour  skin  bodytype  limbs  extremities  teeth  personality  \
0                                                                          
black        1.0   0.0       0.0    0.0          0.0    0.0          0.0   
white        1.0   0.0       0.0    0.0          0.0    0.0          0.0   
blue         1.0   0.0       0.0    0.0          0.0    0.0          0.0   
brown        1.0   0.0       0.0    0.0          0.0    0.0          0.0   
gray         1.0   0.0       0.0    0.0          0.0    0.0          0.0   
...          ...   ...       ...    ...          ...    ...          ...   
smart        0.0   0.0       0.0    0.0          0.0    0.0          1.0   
group        0.0   0.0       0.0    0.0          0.0    0.0          1.0   
solitary     0.0   0.0       0.0    0.0          0.0    0.0          1.0   
nestspot     0.0   0.0       0.0    0.0          0.0    0.0          1.0   
domestic     0.0   0.0       0.0    0.0          0.0    0.0          1.0   

          m

In [88]:
dataset = pd.concat([data,concepts],axis = 0)
print(dataset)

            black white blue brown gray orange  red yellow patches spots  ...  \
antelope        0     0    0     0    0      0    0      0       0     0  ...   
grizzlybear     1     0    0     1    0      0    0      0       0     0  ...   
killerwhale     1     1    0     0    0      0    0      0       1     1  ...   
beaver          0     0    0     1    0      0    0      0       0     0  ...   
dalmatian       1     1    0     0    0      0    0      0       1     1  ...   
...           ...   ...  ...   ...  ...    ...  ...    ...     ...   ...  ...   
smart         NaN   NaN  NaN   NaN  NaN    NaN  NaN    NaN     NaN   NaN  ...   
group         NaN   NaN  NaN   NaN  NaN    NaN  NaN    NaN     NaN   NaN  ...   
solitary      NaN   NaN  NaN   NaN  NaN    NaN  NaN    NaN     NaN   NaN  ...   
nestspot      NaN   NaN  NaN   NaN  NaN    NaN  NaN    NaN     NaN   NaN  ...   
domestic      NaN   NaN  NaN   NaN  NaN    NaN  NaN    NaN     NaN   NaN  ...   

            colour skin bod

In [46]:
dataset = pd.concat([data,concepts],axis = 0)
print(dataset)

0              black white blue brown gray orange  red yellow patches spots  \
antelope           0     0    0     0    0      0    0      0       0     0   
grizzlybear        1     0    0     1    0      0    0      0       0     0   
killerwhale        1     1    0     0    0      0    0      0       1     1   
beaver             0     0    0     1    0      0    0      0       0     0   
dalmatian          1     1    0     0    0      0    0      0       1     1   
persiancat         0     1    1     0    1      0    0      0       0     0   
horse              1     1    0     1    1      0    0      0       1     0   
germanshepherd     1     0    0     1    1      0    0      0       1     0   
bluewhale          0     0    1     0    1      0    0      0       0     1   
siamesecat         1     1    0     1    1      0    0      0       1     0   
skunk              1     1    0     0    0      0    0      0       0     0   
mole               1     0    0     1    1      0   

In [11]:
print(data.index)

Index(['antelope', 'grizzlybear', 'killerwhale', 'beaver', 'dalmatian',
       'persiancat', 'horse', 'germanshepherd', 'bluewhale', 'siamesecat',
       'skunk', 'mole', 'tiger', 'hippopotamus', 'leopard', 'moose',
       'spidermonkey', 'humpbackwhale', 'elephant', 'gorilla', 'ox', 'fox',
       'sheep', 'seal', 'chimpanzee', 'hamster', 'squirrel', 'rhinoceros',
       'rabbit', 'bat', 'giraffe', 'wolf', 'chihuahua', 'rat', 'weasel',
       'otter', 'buffalo', 'zebra', 'giantpanda', 'deer', 'bobcat', 'pig',
       'lion', 'mouse', 'polarbear', 'collie', 'walrus', 'raccoon', 'cow',
       'dolphin'],
      dtype='object')


In [ ]:
i = ['antelope', 'grizzlybear', 'killerwhale', 'beaver', 'dalmatian',
       'persiancat', 'horse', 'germanshepherd', 'bluewhale', 'siamesecat',
       'skunk', 'mole', 'tiger', 'hippopotamus', 'leopard', 'moose',
       'spidermonkey', 'humpbackwhale', 'elephant', 'gorilla', 'ox', 'fox',
       'sheep', 'seal', 'chimpanzee', 'hamster', 'squirrel', 'rhinoceros',
       'rabbit', 'bat', 'giraffe', 'wolf', 'chihuahua', 'rat', 'weasel',
       'otter', 'buffalo', 'zebra', 'giantpanda', 'deer', 'bobcat', 'pig',
       'lion', 'mouse', 'polarbear', 'collie', 'walrus', 'raccoon', 'cow',
       'dolphin']
for i,j in data:
  data[i,'colour'] = 

In [ ]:
Y = data['forest']
data = data.drop(['forest'], axis=1)
print(Y)
print(data)

antelope          0
grizzlybear       1
killerwhale       0
beaver            0
dalmatian         0
persiancat        0
horse             0
germanshepherd    0
bluewhale         0
siamesecat        0
skunk             1
mole              1
tiger             1
hippopotamus      0
leopard           0
moose             1
spidermonkey      1
humpbackwhale     0
elephant          0
gorilla           1
ox                0
fox               1
sheep             0
seal              0
chimpanzee        1
hamster           0
squirrel          1
rhinoceros        0
rabbit            1
bat               1
giraffe           0
wolf              1
chihuahua         0
rat               1
weasel            1
otter             1
buffalo           0
zebra             0
giantpanda        1
deer              1
bobcat            1
pig               0
lion              1
mouse             1
polarbear         0
collie            0
walrus            0
raccoon           1
cow               0
dolphin           0


In [ ]:
X = data.values
print(X)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 0 ... 1 1 0]
 [1 1 0 ... 0 0 1]
 [0 1 1 ... 0 0 1]]


In [ ]:
X.flatten()
print(X)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 0 ... 1 1 0]
 [1 1 0 ... 0 0 1]
 [0 1 1 ... 0 0 1]]


In [ ]:
import torch
X_tensor = torch.Tensor(X)

TypeError: ignored

In [ ]:
train = data[:35]
print(train)
test = data[35:]
print(test)

0              black white blue brown gray orange red yellow patches spots  \
antelope           0     0    0     0    0      0   0      0       0     0   
grizzlybear        1     0    0     1    0      0   0      0       0     0   
killerwhale        1     1    0     0    0      0   0      0       1     1   
beaver             0     0    0     1    0      0   0      0       0     0   
dalmatian          1     1    0     0    0      0   0      0       1     1   
persiancat         0     1    1     0    1      0   0      0       0     0   
horse              1     1    0     1    1      0   0      0       1     0   
germanshepherd     1     0    0     1    1      0   0      0       1     0   
bluewhale          0     0    1     0    1      0   0      0       0     1   
siamesecat         1     1    0     1    1      0   0      0       1     0   
skunk              1     1    0     0    0      0   0      0       0     0   
mole               1     0    0     1    1      0   0      0    

In [ ]:
Y_train = train['forest']
# print(Y_train)
Y_test = test['forest']
headers = list(data.columns)

# print the list of headers
print(headers)
X_train = train[['black', 'white', 'blue', 'brown', 'gray', 'orange', 'red', 'yellow', 'patches', 'spots', 'stripes', 'furry', 'hairless', 'toughskin', 'big', 'small', 'bulbous', 'lean', 'flippers', 'hands', 'hooves', 'pads', 'paws', 'longleg', 'longneck', 'tail', 'chewteeth', 'meatteeth', 'buckteeth', 'strainteeth', 'horns', 'claws', 'tusks', 'smelly', 'flys', 'hops', 'swims', 'tunnels', 'walks', 'fast', 'slow', 'strong', 'weak', 'muscle', 'bipedal', 'quadrapedal', 'active', 'inactive', 'nocturnal', 'hibernate', 'agility', 'fish', 'meat', 'plankton', 'vegetation', 'insects', 'forager', 'grazer', 'hunter', 'scavenger', 'skimmer', 'stalker', 'newworld', 'oldworld', 'arctic', 'coastal', 'desert', 'bush', 'plains', 'fields', 'jungle', 'mountains', 'ocean', 'ground', 'water', 'tree', 'cave', 'fierce', 'timid', 'smart', 'group', 'solitary', 'nestspot', 'domestic']]
X_test = test[['black', 'white', 'blue', 'brown', 'gray', 'orange', 'red', 'yellow', 'patches', 'spots', 'stripes', 'furry', 'hairless', 'toughskin', 'big', 'small', 'bulbous', 'lean', 'flippers', 'hands', 'hooves', 'pads', 'paws', 'longleg', 'longneck', 'tail', 'chewteeth', 'meatteeth', 'buckteeth', 'strainteeth', 'horns', 'claws', 'tusks', 'smelly', 'flys', 'hops', 'swims', 'tunnels', 'walks', 'fast', 'slow', 'strong', 'weak', 'muscle', 'bipedal', 'quadrapedal', 'active', 'inactive', 'nocturnal', 'hibernate', 'agility', 'fish', 'meat', 'plankton', 'vegetation', 'insects', 'forager', 'grazer', 'hunter', 'scavenger', 'skimmer', 'stalker', 'newworld', 'oldworld', 'arctic', 'coastal', 'desert', 'bush', 'plains', 'fields', 'jungle', 'mountains', 'ocean', 'ground', 'water', 'tree', 'cave', 'fierce', 'timid', 'smart', 'group', 'solitary', 'nestspot', 'domestic']]
# X_train = train.iloc[0:34, 0:84]
# print(X_train)
# X_test = test.iloc[0:14, 0:84]

['black', 'white', 'blue', 'brown', 'gray', 'orange', 'red', 'yellow', 'patches', 'spots', 'stripes', 'furry', 'hairless', 'toughskin', 'big', 'small', 'bulbous', 'lean', 'flippers', 'hands', 'hooves', 'pads', 'paws', 'longleg', 'longneck', 'tail', 'chewteeth', 'meatteeth', 'buckteeth', 'strainteeth', 'horns', 'claws', 'tusks', 'smelly', 'flys', 'hops', 'swims', 'tunnels', 'walks', 'fast', 'slow', 'strong', 'weak', 'muscle', 'bipedal', 'quadrapedal', 'active', 'inactive', 'nocturnal', 'hibernate', 'agility', 'fish', 'meat', 'plankton', 'vegetation', 'insects', 'forager', 'grazer', 'hunter', 'scavenger', 'skimmer', 'stalker', 'newworld', 'oldworld', 'arctic', 'coastal', 'desert', 'bush', 'plains', 'fields', 'jungle', 'mountains', 'ocean', 'ground', 'water', 'tree', 'cave', 'fierce', 'timid', 'smart', 'group', 'solitary', 'nestspot', 'domestic', 'forest']


In [ ]:
Y = Y_train.values
X = X_train.values
Y_test = Y_test.values
X_test = X_test.values

In [ ]:
for element in X:
    print(type(element))
for element in Y:
    print(type(element))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# convert the data to PyTorch tensors
X_train_tensor = torch.Tensor(X)
X_test_tensor = torch.Tensor(X_test)
y_train_tensor = torch.Tensor(Y)
y_test_tensor = torch.Tensor(Y_test)

# define the logistic regression model
class LogisticRegression(nn.Module):
    def __init__(self, input_size):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_size, 1)
    
    def forward(self, x):
        x = self.linear(x)
        return x

# create an instance of the logistic regression model
model = LogisticRegression(input_size=X_train.shape[1])

# define the loss function and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# create PyTorch dataloaders for the train and test sets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

# train the model
n_epochs = 100
for epoch in range(n_epochs):
    running_loss = 0.0
    for i, data in enumerate(train_loader):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs.squeeze(), labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f'Epoch {epoch+1}: loss={running_loss/len(train_loader)}')

TypeError: ignored